#!/bin/bash
# ==============================================================================
# Script: Automated Git Release Manager
# Purpose: Parses main script for version/changes, updates README, and pushes to GitHub.
# Author: Babak Sorkhpour
# ==============================================================================

MAIN_SCRIPT="conduit-optimizer.sh"
README_FILE="README.md"

# 1. EXTRACT METADATA FROM MAIN SCRIPT
echo ">> extracting metadata from $MAIN_SCRIPT..."

# Get Version (grep "Version: x.x.x")
VERSION=$(grep "^# Version:" "$MAIN_SCRIPT" | awk '{print $3}')

# Get Release Notes (Extract text between <release_notes> tags)
# We remove the '#' comment characters to make it clean Markdown
RELEASE_NOTES=$(sed -n '/<release_notes>/,/<\/release_notes>/p' "$MAIN_SCRIPT" | sed '1d;$d' | sed 's/^# //')

if [[ -z "$VERSION" ]]; then
    echo "Error: Could not detect version in $MAIN_SCRIPT"
    exit 1
fi

echo "   Detected Version: $VERSION"

# 2. GENERATE / UPDATE README.md
echo ">> Updating $README_FILE..."

cat > "$README_FILE" <<EOF
# Conduit Console & Optimizer Tools
> **Repository:** [https://github.com/babakskr/Conduit-console](https://github.com/babakskr/Conduit-console)  
> **Maintainer:** Babak Sorkhpour  
> **Latest Version:** $VERSION

## 🛠 Project Tools Overview

| Tool File | Description | Usage |
| :--- | :--- | :--- |
| \`conduit-optimizer.sh\` | Performance tuner for Docker & Native instances. Adjusts CPU/IO Priority. | \`sudo ./conduit-optimizer.sh -h\` |
| \`AI_DEV_GUIDELINES.md\` | Protocol and System Prompts for AI-assisted development (En/Fa). | Reference Doc |
| \`git_op.sh\` | Automated Release Manager & README Generator. | \`./git_op.sh\` |

## 🚀 How to Use: Conduit Optimizer

The optimizer intelligently adjusts the Linux Priority (PRI) of your running Conduit processes to prevent lag.

### Installation
\`\`\`bash
git clone https://github.com/babakskr/Conduit-console.git
cd Conduit-console
chmod +x conduit-optimizer.sh
\`\`\`

### Basic Usage (Default Mode)
Automatically sets **Docker to PRI 10** (High) and **Native to PRI 15** (Medium-High).
\`\`\`bash
sudo ./conduit-optimizer.sh
\`\`\`

### Custom Usage (CLI Arguments)
You can manually set the target Priority (Range 5-20). 
*Lower value = Higher Priority in manual input? No, we follow Linux PRI logic:*
* **10**: Very High Priority (Nice -10)
* **20**: Normal Priority (Nice 0)

\`\`\`bash
# Example: Set Docker to PRI 10 and Native to PRI 18 (almost normal)
sudo ./conduit-optimizer.sh -dock 10 -srv 18

# Example: Skip Docker, only optimize Service to PRI 5 (Maximum Power)
sudo ./conduit-optimizer.sh -dock 0 -srv 5

# Get Help
./conduit-optimizer.sh -h
\`\`\`

## 📜 Latest Release Notes ($VERSION)
$RELEASE_NOTES

---
*Auto-generated by git_op.sh*
EOF

# 3. GIT OPERATIONS
echo ">> Staging files..."
git add .

echo ">> Committing..."
git commit -m "release: v$VERSION - updated optimizer logic and docs"

echo ">> Tagging v$VERSION..."
git tag -a "v$VERSION" -m "Automated Release v$VERSION"

echo ">> Pushing to GitHub..."
git push origin main
git push origin "v$VERSION"

# 4. GITHUB RELEASE (VIA CLI)
if command -v gh &> /dev/null; then
    echo ">> Creating GitHub Release..."
    gh release create "v$VERSION" \
       --title "Release v$VERSION" \
       --notes "$RELEASE_NOTES"
    echo "✅ Release Published Successfully!"
else
    echo "⚠️  GitHub CLI (gh) not installed. Pushed tags only."
fi