Feature: Help and documentation contract
  As a user
  I want consistent help output and docs workflow
  So that operational guidance remains predictable

  @critical @docs @KR-008
  Scenario: Contract: help output includes required sections
    Given a project script supports -h
    When the help command is executed
    Then output contains Description
    And output contains Usage
    And output contains Options
    And output contains Examples

  @docs @release
  Scenario: Contract: README is generated by git_op workflow
    Given documentation changes are prepared
    When release workflow is executed
    Then README is treated as generated output
    And manual drift is avoided by git_op automation
